import buildoptions as bop


Import('env')

env.Append(CFLAGS=bop.GLOBAL_CFLAGS)
env.Append(CXXFLAGS=bop.GLOBAL_CXXFLAGS)
env.Append(F90FLAGS=bop.GLOBAL_FFLAGS)

env.Append(CPPPATH=bop.MPI_INCDIR+bop.SOLVERIO_INCDIR+bop.BOOSTCPP_INCDIR)
env.Append(CPPPATH=bop.PETSC_INCDIR+bop.METIS_INCDIR+bop.VTK_INCDIR)
env.Append(CPPPATH=bop.GOOGLETEST_INCDIR)
env.Append(F90PATH=bop.MPI_INCDIR)

env.Append(LIBPATH=bop.PETSC_LIBSDIR+bop.MPI_LIBSDIR+bop.METIS_LIBSDIR+bop.RUNTIME_LIBSDIR)

env.Prepend(LIBS=bop.MPI_LIBSLIST)
env.Append(LIBS=bop.METIS_LIBSLIST+bop.RUNTIME_LIBSLIST)
env.Append(LIBS=bop.PETSC_LIBSLIST)

sources="""
	cvSolverIO.cxx
	""".split()

object_list=env.Object(source=sources)

# Strip out the .mod files (not needed for linking!)
object_list_withoutDotModFiles = [object_list for object_list in object_list if object_list.get_suffix() == ".o"]


# Set the source and output file name ("target"):
default = env.Library(target='libcrimson_solverio.a', source=object_list_withoutDotModFiles)
copyLibrary = env.Command("../../lib/libcrimson_solverio.a", "./libcrimson_solverio.a", Copy("$TARGET", "$SOURCE"))

Default(default,copyLibrary)
