import buildoptions as bop
import string


Import('env')

env.Append(CFLAGS=bop.GLOBAL_CFLAGS)
env.Append(CXXFLAGS=bop.GLOBAL_CXXFLAGS)
env.Append(F90FLAGS=bop.GLOBAL_FFLAGS)

env.Append(CFLAGS=bop.LESLIB_DEFS)
env.Append(CPPPATH=bop.MPI_INCDIR+bop.LESLIB_INCDIR+bop.SOLVERIO_INCDIR+bop.BOOSTCPP_INCDIR)
env.Append(CXXFLAGS=bop.LESLIB_DEFS)
env.Append(CPPPATH=bop.PETSC_INCDIR+bop.METIS_INCDIR+bop.VTK_INCDIR)
env.Append(CPPPATH=bop.GOOGLETEST_INCDIR)
env.Append(F90FLAGS=bop.LESLIB_DEFS)
env.Append(F90PATH=bop.MPI_INCDIR+bop.LESLIB_INCDIR)

env.Append(LIBPATH=bop.PETSC_LIBSDIR+bop.MPI_LIBSDIR+bop.METIS_LIBSDIR+bop.INTEL_LIBSDIR+bop.LESLIB_LIBSDIR)

env.Prepend(LIBS=bop.MPI_LIBSLIST)
env.Prepend(LIBS=bop.LESLIB_LIBSLIST)
env.Append(LIBS=bop.METIS_LIBSLIST+bop.INTEL_LIBSLIST)
env.Append(LIBS=bop.PETSC_LIBSLIST)

# HDRS	= cvSolverIO.h
# CXXSRCS = cvSolverIO.cxx

sources=string.split("""
	cvSolverIO.cxx
	""")

object_list=env.Object(source=sources)

# Strip out the .mod files (not needed for linking!)
object_list_withoutDotModFiles = [object_list for object_list in object_list if object_list.get_suffix() == ".o"]


# Set the source and output file name ("target"):
default = env.Library(target='libsimvascular_solverio.a', source=object_list_withoutDotModFiles)
copyLibrary = env.Command("../../lib/libsimvascular_solverio.a", "./libsimvascular_solverio.a", Copy("$TARGET", "$SOURCE"))

# copy.execute()
# Define SCons' default action:
Default(default,copyLibrary)

# SRCS	= $(CSRCS) $(CXXSRCS)

# OBJS	= $(CSRCS:.c=.$(OBJECTEXT)) $(CXXSRCS:.cxx=.$(OBJECTEXT))

# TARGET_LIB = libsimvascular_solverio.$(STATICEXT)

# $(TOP)/lib/$(TARGET_LIB) : $(OBJS)
# 	$(AR)$(TARGET_LIB) $(OBJS)
# 	mv $(TARGET_LIB) $(TOP)/lib
	
# clean:
# 	-$(RM) $(OBJS) $(TOP)/lib/$(TARGET_LIB) *.pdb *.manifest
