#ifndef AUTOGENERATEDVERSIONNUMBER_HXX_
#define AUTOGENERATEDVERSIONNUMBER_HXX_

// This is a dummy version of this file, in case we're not running SCONS
// (SCONS does the generation of the real version of this file).
#include <cstdio>

void getBuildNumber(char* buildNumber)
{
	sprintf(buildNumber,"UNKNOWN - not built with scons!");
}

void getBuildTime(char* buildTimestamp)
{
	sprintf(buildTimestamp,"UNKNOWN DATE");
}

#endif