/* This file provides interface functions for 'partial ' random 
   access into the PHASTA input files 

   Anil Karanam March 2001 */

#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include <stdlib.h>
#include <time.h>

#ifdef intel
#include <winsock2.h>
#define Write_Restart WRITE_RESTART
#define Write_Error   WRITE_ERROR
#define Write_Displ   WRITE_DISPL
#define Write_Distl   WRITE_DISTL
#else
#include <unistd.h>
#include <strings.h>
#if (!defined IBM )
#define Write_Restart write_restart_
#define Write_Error   write_error_
#define Write_Displ   write_displ_
#define Write_Distl   write_distl_
#else
#define Write_Restart write_restart
#define Write_Error   write_error
#define Write_Displ   write_displ
#define Write_Distl   write_distl
#endif
#endif

#include "mpi.h"
#include "cvSolverIO.h"
#include "common_c.h"

void 
Write_Restart(  int* pid, 
                int* stepno, 
                int* nshg, 
                int* numVars,
                double* array1, 
                double* array2 ) {

    char fname[255];
    char rfile[60];
    char existingfile[30], linkfile[30];
    int irstou;
    int magic_number = 362436;
    int* mptr = &magic_number;
    time_t timenow = time ( &timenow);
    double version=0.0;
    int isize, nitems;
    int iarray[10];
    MPI_Comm iNewComm_C = MPI_Comm_f2c(newcom.iNewComm);

    sprintf(rfile,"restart.%d.%d",*stepno,*pid+1);
    openfile_(rfile,"write", &irstou);

    /* writing the top ascii header for the restart file */

    writestring_( &irstou,"# PHASTA Input File Version 2.0\n");
    writestring_( &irstou,
                  "# format \"keyphrase : sizeofnextblock usual headers\"\n");

    bzero_old( (void*)fname, 255 );
    sprintf(fname,"# Output generated by phasta version (NOT YET CURRENT): %lf \n", version);
    writestring_( &irstou, fname );

    bzero_old( (void*)fname, 255 );
    gethostname(fname,255);
    writestring_( &irstou,"# This result was produced on: ");
    writestring_( &irstou, fname );
    writestring_( &irstou,"\n");

    bzero_old( (void*)fname, 255 );
    sprintf(fname,"# %s\n", ctime( &timenow ));
    writestring_( &irstou, fname );

    isize = 1;
    nitems = 1;
    iarray[ 0 ] = 1;
    writeheader_( &irstou, "byteorder magic number ", 
                  (void*)iarray, &nitems, &isize, "integer", outpar.iotype );
    
    nitems = 1;
    writedatablock_( &irstou, "byteorder magic number ",
                     (void*)mptr, &nitems, "integer", outpar.iotype );
    
    
    bzero_old( (void*)fname, 255 );
    sprintf(fname,"number of modes : < 0 > %d\n", *nshg);
    writestring_( &irstou, fname );
    
    bzero_old( (void*)fname, 255 );
    sprintf(fname,"number of variables : < 0 > %d\n", *numVars);
    writestring_( &irstou, fname );
        
    
    isize = (*nshg)*(*numVars);
    nitems = 3;
    iarray[ 0 ] = (*nshg);
    iarray[ 1 ] = (*numVars);
    iarray[ 2 ] = (*stepno);
    writeheader_( &irstou, "solution ", 
                  (void*)iarray, &nitems, &isize, "double", outpar.iotype );
    
        
    nitems = (*nshg)*(*numVars);
    writedatablock_( &irstou, "solution ",
                     (void*)(array1), &nitems, "double", outpar.iotype );
        
   

    nitems = 3;
    writeheader_( &irstou, "time derivative of solution ", 
                  (void*)iarray, &nitems, &isize, "double", outpar.iotype );
    
    
    nitems = (*nshg)*(*numVars);
    writedatablock_( &irstou, "time derivative of solution ",
                     (void*)(array2), &nitems, "double", outpar.iotype );

        
    closefile_( &irstou, "write" );
      
    MPI_Barrier(iNewComm_C);

    ///* create a soft link of the restart we just wrote to restart.latest
    // this is the file the next run will always try to start from */

    //sprintf( linkfile, "restart.latest.%d", *pid+1 );
    //unlink( linkfile );
    //sprintf( existingfile, "restart.%d.%d", *stepno, *pid+1 );
    //link( existingfile, linkfile );
}

void 
Write_Error(  int* pid, 
              int* stepno, 
              int* nshg, 
              int* numVars,
              double* array1 ) { 


    char fname[255];
    char rfile[60];
    int irstou;
    int magic_number = 362436;
    int* mptr = &magic_number;
    time_t timenow = time ( &timenow);
    double version=0.0;
    int isize, nitems;
    int iarray[10];

    sprintf(rfile,"restart.%d.%d",*stepno,*pid+1);
    openfile_(rfile,"append", &irstou);

    isize = (*nshg)*(*numVars);
    nitems = 3;
    iarray[ 0 ] = (*nshg);
    iarray[ 1 ] = (*numVars);
    iarray[ 2 ] = (*stepno);
    writeheader_( &irstou, "errors", (void*)iarray, &nitems, &isize, "double", outpar.iotype );
    
        
    nitems = (*nshg)*(*numVars);
    writedatablock_( &irstou, "errors ", (void*)(array1), &nitems, "double", outpar.iotype );

    closefile_( &irstou, "append" );
    
}


void 
Write_Displ(  int* pid, 
              int* stepno, 
              int* nshg, 
              int* numVars,
              double* array1,
              double* array2) {


    char fname[255];
    char rfile[60];
    int irstou;
    int magic_number = 362436;
    int* mptr = &magic_number;
    time_t timenow = time ( &timenow);
    double version=0.0;
    int isize, nitems;
    int iarray[10];

    sprintf(rfile,"restart.%d.%d",*stepno,*pid+1);
    openfile_(rfile,"append", &irstou);

    isize = (*nshg)*(*numVars);
    nitems = 3;
    iarray[ 0 ] = (*nshg);
    iarray[ 1 ] = (*numVars);
    iarray[ 2 ] = (*stepno);
    writeheader_( &irstou, "displacement", (void*)iarray, &nitems, &isize, "double", outpar.iotype );
    
        
    nitems = (*nshg)*(*numVars);
    writedatablock_( &irstou, "displacement", (void*)(array1), &nitems, "double", outpar.iotype );

    nitems = 3;
    writeheader_( &irstou, "displacement_ref", (void*)iarray, &nitems, &isize, "double", outpar.iotype );

    nitems = (*nshg)*(*numVars);
    writedatablock_( &irstou, "displacement_ref", (void*)(array2), &nitems, "double", outpar.iotype );

    closefile_( &irstou, "append" );
    
}

void 
Write_Distl(  int* pid, 
              int* stepno, 
              int* nshg, 
              int* numVars,
              double* array1 ) { 


    char fname[255];
    char rfile[60];
    int irstou;
    int magic_number = 362436;
    int* mptr = &magic_number;
    time_t timenow = time ( &timenow);
    double version=0.0;
    int isize, nitems;
    int iarray[10];

    sprintf(rfile,"restart.%d.%d",*stepno,*pid+1);
    openfile_(rfile,"append", &irstou);

    isize = (*nshg)*(*numVars);
    nitems = 3;
    iarray[ 0 ] = (*nshg);
    iarray[ 1 ] = (*numVars);
    iarray[ 2 ] = (*stepno);
    writeheader_( &irstou, "distances", (void*)iarray, &nitems, &isize, "double", outpar.iotype );
    
        
    nitems = (*nshg)*(*numVars);
    writedatablock_( &irstou, "distances", (void*)(array1), &nitems, "double", outpar.iotype );

    closefile_( &irstou, "append" );
    
}



