#!/bin/bash

if [ $# -lt 4 ]
  then
  echo "Usage: $0 start_index end_index increment folder_name"
fi

if [ $# -ge 4 ]
  then

# reduce the restarts for each time step requested

k=0
for ((i=$1 ;i<=$2; i+=$3)); 
do
  echo "Multipostsolver is reducing timestep: $i"
  let k++
  /home/carthurs/workspace/hg_simvascular/simvascular_systemic/bin/postsolver -sn $i -newsn $i -ph -td -bflux -wss $5 $6
done

# now create the Paraview PHT file

echo '<?xml version="1.0" ?>' > view.pht
echo '<PhastaMetaFile number_of_pieces="1">' >> view.pht
echo '  <GeometryFileNamePattern pattern="geombc.dat.%d" has_piece_entry="1" has_time_entry="0"/>' >> view.pht
echo '  <FieldFileNamePattern pattern="restart.%d.0" has_piece_entry="0" has_time_entry="1"/>' >> view.pht
echo '  <TimeSteps number_of_steps="'$k'" auto_generate_indices="1"' >> view.pht
echo '                                    start_index="'$1'"' >> view.pht
echo '                                    increment_index_by="'$3'"' >> view.pht
echo '                                    start_value="0."' >> view.pht
echo '                                    increment_value_by="1">' >> view.pht
echo '</TimeSteps>' >> view.pht
if [ "$5" == "-disp" ]; then
  echo '<Fields number_of_fields="5">' >> view.pht
else
  echo '<Fields number_of_fields="4">' >> view.pht
fi
echo '  <Field paraview_field_tag="velocity"' >> view.pht
echo '         phasta_field_tag="solution"' >> view.pht
echo '         start_index_in_phasta_array="1"' >> view.pht
echo '         number_of_components="3"' >> view.pht
echo '         data_dependency="0"' >> view.pht
echo '         data_type="double"/>' >> view.pht
echo '  <Field paraview_field_tag="pressure"' >> view.pht
echo '         phasta_field_tag="solution"' >> view.pht
echo '         start_index_in_phasta_array="0"' >> view.pht
echo '         number_of_components="1"' >> view.pht
echo '         data_dependency="0"' >> view.pht
echo '         data_type="double"/>' >> view.pht
echo '  <Field paraview_field_tag="wall shear stresses"' >> view.pht
echo '         phasta_field_tag="wall shear stresses"' >> view.pht
echo '         start_index_in_phasta_array="0"' >> view.pht
echo '         number_of_components="3"' >> view.pht
echo '         data_dependency="0"' >> view.pht
echo '         data_type="double"/>' >> view.pht  
echo '  <Field paraview_field_tag="boundary fluxes"' >> view.pht
echo '         phasta_field_tag="boundary fluxes"' >> view.pht
echo '         start_index_in_phasta_array="1"' >> view.pht
echo '         number_of_components="3"' >> view.pht
echo '         data_dependency="0"' >> view.pht
echo '         data_type="double"/>' >> view.pht    
if [ "$5" == "-disp" ]; then
  echo '  <Field paraview_field_tag="displacement"' >> view.pht
  echo '         phasta_field_tag="displacement"' >> view.pht
  echo '         start_index_in_phasta_array="0"' >> view.pht
  echo '         number_of_components="3"' >> view.pht
  echo '         data_dependency="0"' >> view.pht
  echo '         data_type="double"/>' >> view.pht    
fi
echo '</Fields>' >> view.pht
echo '</PhastaMetaFile>' >> view.pht

# now make a folder to store the reduced restarts and pht file

cd ..
newdir="restarts-"$4"-"$1"-"$2"-"$3
mkdir $newdir
cp geombc.dat.1 ./$newdir
cp solver.inp ./$newdir

cd -

cp *.dat ../$newdir

mv *.0 view.pht ../$newdir

echo ""
echo "Restarts copied to " $newdir
echo ""

fi
