import buildoptions as bop


Import('env')

env_local = env.Clone()

env_local.Append(CFLAGS=bop.GLOBAL_CFLAGS)
env_local.Append(CXXFLAGS=bop.GLOBAL_CXXFLAGS)
env_local.Append(F90FLAGS=bop.GLOBAL_FFLAGS)

env_local.Append(CPPPATH=bop.GOOGLETEST_INCDIR+bop.FLOWSOLVER_INCDIR+bop.ESTIMATOR_INCDIR)
# env_local.Append(CPPPATH=[bop.GOOGLETEST_TOP])

env_local.Prepend(LIBPATH=bop.BOOSTCPP_LIBSDIR)
env_local.Append(LIBS=bop.BOOSTCPP_LIBSLIST)

env_local.Prepend(LIBS=bop.GOOGLETEST_LIBSLIST)
env_local.Prepend(LIBS=bop.FLOWSOLVER_LIBSLIST)
env_local.Append(LIBS=bop.CRIMSON_COMMON_LIBSLIST)

sources="""
	testMultidom.cxx
	testFileReaders.cxx
	testMain.cxx
	testOrphans.cxx
	testMainWithZeroDDomain.cxx
	""".split()

object_list=env_local.Object(source=sources)

# Set the source and output file name ("target"):
default = env_local.Library(target='libtest_flowsolver.a', source=object_list)
copyLibrary = env_local.Command("../../lib/libtest_flowsolver.a", "./libtest_flowsolver.a", Copy("$TARGET", "$SOURCE"))

# Define SCons' default action:
Default(default,copyLibrary)
